name: laom
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ffmpeg
  - pip:
      - -r requirements.txt
      - numpy
      - pandas
      - scipy
      - scikit-image
      - h5py
      - opencv-python
